spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: user
    password: password
  #    type: com.zaxxer.hikari.HikariDataSource
  #    hikari:
  #      connection-test-query: SELECT 1;
  jpa:
    hibernate:
      ddl-auto: create
    #      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  flyway:
    validateOnMigrate: false

value:
  borderTime: "11:00:00"
security:
  timeToLive: 3600
  secret: foigfdoigj
  header: Authorization