spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voter
    username: user
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1;
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
value:
  borderTime: "11:00:00"
security:
  timeToLive: 3600
  secret: foigfdoigj
  header: Authorization